//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projemynei.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilgiler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bilgiler()
        {
            this.Kullanicilars = new HashSet<Kullanicilar>();
            this.Saticilars = new HashSet<Saticilar>();
        }
    
        public string TelNo { get; set; }
        public string Adres { get; set; }
        public int BilgilerID { get; set; }
        public string Email { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanicilar> Kullanicilars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Saticilar> Saticilars { get; set; }
    }
}
