//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projemynei.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saticilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Saticilar()
        {
            this.Urunlers = new HashSet<Urunler>();
        }
    
        public int SaticiID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<int> BilgilerID { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public string GizliSoru { get; set; }
        public string GizliCevap { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> UserType { get; set; }
    
        public virtual Bilgiler Bilgiler { get; set; }
        public virtual Urunler Urunler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urunler> Urunlers { get; set; }
    }
}
