//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projemynei.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int SepetID { get; set; }
        public Nullable<int> SatisID { get; set; }
        public Nullable<int> UrunID { get; set; }
    
        public virtual Sati Sati { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
